/**
 * index.ts
 * 
 * Main KoaCart server file
 */

/**
 * Koa
 * 
 * Koa Application
 * @url https://www.npmjs.com/package/koa
 */
import * as Koa from 'koa';

/**
 * serve
 * 
 * Koa Static to serve static files
 * @url https://www.npmjs.com/package/koa-static
 */
import * as serve from 'koa-static';

/**
 * mongoose
 * 
 * MongoDB ORM
 * @url https://www.npmjs.com/package/mongoose
 */
import * as mongoose from 'mongoose';

/**
 * ApolloServer
 * 
 * Apollo Server for Koa
 * 
 * @https://www.npmjs.com/package/apollo-server-koa
 */
import { ApolloServer } from 'apollo-server-koa';

/**
 * http2
 * 
 * NodeJs http2 server
 */
import * as http2 from 'http2';

/**
 * readFileSync
 * 
 * Help to read file in sync
 */
import { readFileSync } from 'fs';

/**
 * config
 * 
 * KoaCart application configuration
 */
import config from './server/config';

/**
 * schema
 * 
 * KoaCart application GraphQL schema
 */
import schema from './server/schema';

/**
 * response
 * 
 * Response middleware to track requests and response
 */
import response from './server/middleware/response';

/**
 * logger
 * 
 * Logger utility for KoaCart application
 */
import logger from './server/utility/logger';

/**
 * getTemplatePath
 * 
 * Utility method to access HTML template path generated by Angular
 */
import { getTemplatePath } from './server/utility/helper';

/**
 * universal
 * 
 * middleware for angular universal
 */
import universal from './server/middleware/universal';

/**
 * server
 * 
 * AplloServer
 */
const server: ApolloServer = new ApolloServer(schema);

/**
 * mongoose setup
 * 
 * Setting up the mongoose to connect with MongoDb database
 */
mongoose.connect(config.database.URI, {
  useNewUrlParser: true
});
mongoose.connection.on('error', error => {
  logger.error(error);
});

/**
 * app
 * 
 * Koa app
 */
const app: Koa = new Koa();

app
  .use(response)
  .use(serve(getTemplatePath(), {
    root: __dirname,
    index: false,
    gzip: true,
    brotli: true
  }))
  .use(universal);

server.applyMiddleware({ app });

if(config.app.PROTOCOL.toLowerCase() === 'https' && config.app.SSL_CERT !== '' && config.app.SSL_KEY !== '') {
  const _server: http2.Http2SecureServer = http2.createSecureServer({
    key: readFileSync(config.app.SSL_KEY, 'utf8'),
    cert: readFileSync(config.app.SSL_CERT, 'utf8')
  }, app.callback()).listen(config.app.PORT, config.app.HOST, () => {
    console.log(`Server started at ${config.app.PROTOCOL}://${config.app.HOST}:${config.app.PORT}`);
    logger.info(`Server started at ${config.app.PROTOCOL}://${config.app.HOST}:${config.app.PORT}`);
  });

  _server.on('error', error => {
    logger.error(error);
  });
}else {
  app.on('error', error => {
    logger.error(error);
  });

  app.listen(config.app.PORT, config.app.HOST, () => {
    console.log(`Server started at ${config.app.PROTOCOL}://${config.app.HOST}:${config.app.PORT}`);
    logger.info(`Server started at ${config.app.PROTOCOL}://${config.app.HOST}:${config.app.PORT}`);
  });
}
